[project]
name = "english-to-hindi-roman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deep-translator>=1.11.4",
    "indic-transliteration>=2.3.75",
    "translators>=6.0.1",
]
